<?php $page = 'about' ?>
<?php include 'includes/header.php' ?>
<!-- ***** About Page ****************************************************** -->
<div class="dk_secondary dk_about_page">
    <section class="dk_hero">
        <div class="row">
            <div class="large-12 columns">
                <h2>About DK Web Design</h2>
            </div>
        </div>
    </section>
    <section class="dk_main_content">
        <div class="row dk_bottom_blue">
            <div class="large-8 medium-7 small-12 columns">
                <h1>Meet Your Local Web Design Team</h1>
                <h2>We're a Web Design Company Located in Chico, CA</h2>
                <p>At DK Web Design, we are focused on building clean, professional websites that meet your business goals. With over 25 years of collective experience, our team members are focused on staying on the cusp of technology and modern practices to ensure that you're getting the most out of your investment.</p>
                <p>DK Web Design is here to support you on your way to success. Our goal is to be a resource for your company in whatever way that means to you; we can have as much or as little control as you'd like. We research options before suggesting solutions, treating your business as we would our own. If you're looking for a company to be your partner in success, DK Web Design is the place for you.</p>
            </div>
            <div class="large-4 medium-5 small-12 columns">
                <img src="img/dkwebdesign-exterior.jpg">
            </div>
        </div>
        <div class="dk_employee_module">
            <div class="row add-padding">
                <div class="large-3 medium-4 small-12 columns" id="teamMainImg">
                    <!-- Employee Main Image will be generated by JSON -->
                </div>
                <div class="large-9 medium-8 small-12 columns">
                    <div class="dk_team_main" id="teamMain">
                        <!-- Employee Main Details will be generated by JSON -->
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="large-12 columns">
                    <div class="dk_team row small-up-2 medium-up-3 large-up-6" id="teamThumbs">
                        <!-- Team Thumbnails will be generated by JSON -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="dk_eggshell">
        <div class="row">
            <div class="large-6 medium-6 small-12 columns dk_add_bot_pad">
                <h2>We Enjoy Giving Back</h2>
                <p>Our owner, Danielle Vogel, is very engaged in the animal welfare community. After opening in 2012, she decided to return some of the business profits to these organizations. DK Web Design makes monetary donations to local non-profit organizations on a regular basis. Our team also provides low or no-cost web development services to non-profit organizations in order to help them achieve their goals without it cutting into their budget. If you have a non-profit and are in need of help with your website, please <a href="contact.php">contact us</a> to get the ball rolling!</p>
                <a class="dk_button dk_primary" href="giving-back-to-chico.php">Learn More</a>
            </div>
            <div class="large-6 medium-6 small-12 columns">
                <h2>Things We Love</h2>
                <div class="row small-up-2 medium-up-2 large-up-4">
                    <div class="column dk_circle_img" alt="Dutch Bros Coffee">
                        <img src="img/dutchbros.jpg">
                    </div>
                    <div class="column dk_circle_img">
                        <img src="img/snowboarding.jpg" alt="Snowboarding">
                    </div>
                    <div class="column dk_circle_img">
                        <img src="img/sushi.jpg" alt="Sushi">
                    </div>
                    <div class="column dk_circle_img">
                        <img src="img/mabel.jpg" alt="We love dogs at DK Web Design">
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
<?php include 'includes/footer.php' ?>
